// SPDX-License-Identifier: Apache-2.0

using System.Collections.Frozen;

namespace Seqvium.Desktop.Presentation;

/// <summary>Stable shell keys; individual unusable entries fall back to English, then an essential host label.</summary>
public sealed class HostLocalizer
{
    private readonly IReadOnlyDictionary<string, string> _english;
    private readonly IReadOnlyDictionary<string, string> _russian;

    public HostLocalizer() : this(English, Russian)
    {
    }

    public HostLocalizer(IReadOnlyDictionary<string, string> english, IReadOnlyDictionary<string, string> russian)
    {
        _english = english.ToFrozenDictionary(StringComparer.Ordinal);
        _russian = russian.ToFrozenDictionary(StringComparer.Ordinal);
    }

    public string Get(string key, HostLanguage language)
    {
        if (language == HostLanguage.Russian && _russian.TryGetValue(key, out var requested) && Usable(requested))
            return requested;
        if (_english.TryGetValue(key, out var fallback) && Usable(fallback)) return fallback;
        // Essential actions stay understandable even if both supplied catalogs are damaged.
        return key switch
        {
            "Window.Minimize" => "Minimize", "Window.Maximize" => "Maximize", "Window.Restore" => "Restore",
            "Window.Close" => "Close", "Project.Unnamed" => "Untitled project",
            "Preference.Language" => "Language", "Preference.Theme" => "Theme", "Host.About" => "About Seqvium",
            _ => language == HostLanguage.Russian ? "Текст недоступен" : "Text unavailable"
        };
    }

    private static bool Usable(string? value) => !string.IsNullOrWhiteSpace(value) &&
                                                 value.Length <= 512 && !value.Any(char.IsControl);

    public static IReadOnlyDictionary<string, string> English { get; } = new Dictionary<string, string>
    {
        ["Workflow.ReadOnly"] = "Read-only",
        ["Workflow.Details"] = "Source and execution details",
        ["Workflow.More"] = "Project actions",
        ["Workflow.Technical"] = "Technical details",
        ["Workflow.GainUnit"] = "Linear amplitude · 0–1 (1 = unity)",
        ["Workflow.NoSelection"] = "No occurrence selected",
        ["Workflow.Busy"] = "An operation is in progress.",
        ["Workflow.NoUndo"] = "No edit to undo.",
        ["Workflow.NoRedo"] = "No edit to redo.",
        ["Workflow.NoTransport"] = "Playback is inactive.",
        ["Status.Ready"] = "Ready",
        ["Status.Playing"] = "Playing",
        ["Status.Stopped"] = "Stopped",
        ["Status.Ended"] = "Ended",
        ["Status.Preparing"] = "Preparing…",
        ["Status.Importing"] = "Importing…",
        ["Status.Saved"] = "Saved",
        ["Status.Cancelled"] = "Cancelled",
        ["Status.Blocked"] = "Playback blocked",
        ["Status.Degraded"] = "Media or processing unavailable",
        ["Status.SaveFailed"] = "Save failed · work retained",
        ["Status.OpenFailed"] = "Open failed · current project retained",
        ["Status.ImportFailed"] = "Import failed",
        ["Status.DeviceFault"] = "Audio output failed",
        ["Status.ActionFailed"] = "Action failed",
        ["Status.LastValid"] = "Previous valid audio",
        ["graph.invalid-gain"] = "Gain must be between 0 and 1.",
        ["graph.prepare-media"] = "Required managed WAV is missing or corrupt.",
        ["graph.prepare-format"] = "Graph channel layout or output format is unsupported.",
        ["graph.prepare-budget"] = "Graph exceeds the supported execution budget.",
        ["graph.prepare-source"] = "Musical source cannot be executed safely.",
        ["graph.prepare-target"] = "Select an available item graph.",
        ["graph.missing-capability"] = "A required node capability is unavailable.",
        ["graph.required-input"] = "A required graph input is not connected.",
        ["graph.missing-output"] = "Graph has no designated Output.",
        ["graph.missing-source"] = "Graph has no bound Source.",
        ["graph.unresolved-source"] = "Source placement or part is unavailable.",
        ["graph.source-coverage"] = "Graph sources do not cover all required parts.",
        ["graph.directed-cycle"] = "Graph contains an unsupported directed cycle.",
        ["graph.unsupported-dependency"] = "Graph has unsupported dependencies.",
        ["graph.unsupported-scope"] = "This processing scope is unsupported.",
        ["graph.processing-limit"] = "Graph exceeds supported node or source counts.",
        ["graph.invalid-declaration"] = "Node declaration is incompatible.",
        ["graph.unsupported-port"] = "A graph port is unsupported.",
        ["graph.missing-endpoint"] = "A connected node or port is unavailable.",
        ["graph.incompatible-ports"] = "Connected ports are incompatible.",
        ["graph.duplicate-connection"] = "Graph contains a duplicate connection.",
        ["graph.input-cardinality"] = "A graph input has too many connections.",
        ["graph.unreachable-source"] = "A Source does not reach Output.",
        ["graph.aggregation"] = "Graph mixing intent is inconsistent.",
        ["graph.preparation-fault"] = "Graph preparation failed.",
        ["graph.preparation-timeout"] = "Graph preparation did not complete; Stop or reopen the project.",
        ["graph.execution-terminated"] = "Audio execution has terminated.",
        ["Workflow.Import"] = "Import WAV",
        ["Workflow.CancelImport"] = "Cancel import",
        ["Workflow.LastValid"] = "Previous valid revision is playing",
        ["Workflow.Open"] = "Open",
        ["Workflow.Save"] = "Save",
        ["Workflow.SaveAs"] = "Save As",
        ["Workflow.Play"] = "Play",
        ["Workflow.Stop"] = "Stop",
        ["Workflow.Panic"] = "Panic",
        ["Workflow.Undo"] = "Undo",
        ["Workflow.Redo"] = "Redo",
        ["Workflow.Discard"] = "Discard",
        ["Workflow.Cancel"] = "Cancel",
        ["Workflow.Occurrence"] = "Musical occurrence",
        ["Workflow.Gain"] = "Gain (amplitude)",
        ["Workflow.Empty"] = "Import a WAV to create a musical occurrence.",
        ["Workflow.Ready"] = "Ready · playback requires Play",
        ["Workflow.Importing"] = "Importing WAV…",
        ["Workflow.ImportFailed"] = "WAV import failed; project was preserved",
        ["Workflow.EditFailed"] = "Edit failed",
        ["Workflow.Cancelled"] = "Import cancelled",
        ["Workflow.Saved"] = "Project saved",
        ["Workflow.SaveFailed"] = "Save failed; unsaved work was retained",
        ["Workflow.OpenFailed"] = "Open failed; current project was retained",
        ["Workflow.Opened"] = "Project opened · press Play to start",
        ["Workflow.Degraded"] = "Media or processing unavailable; project remains accessible",
        ["Workflow.Preparing"] = "Preparing canonical graph…",
        ["Workflow.Playing"] = "Playing selected occurrence",
        ["Workflow.Stopped"] = "Stopped",
        ["Workflow.Ended"] = "Playback ended",
        ["Workflow.Blocked"] = "Playback blocked",
        ["Workflow.DeviceFault"] = "Audio output failed · no automatic restart",
        ["Workflow.DeviceInactive"] = "Output inactive · Windows default output is resolved on Play",
        ["Workflow.CloseFailed"] = "Shutdown failed; resources remain owned",
        ["Workflow.ActionFailed"] = "Action failed",
        ["Workflow.LocalFileRequired"] = "Choose a local file.",
        ["Workflow.UnsavedTitle"] = "Unsaved project",
        ["Workflow.UnsavedPrompt"] = "Save changes before closing or replacing this project?",
        ["Window.Minimize"] = "Minimize", ["Window.Maximize"] = "Maximize", ["Window.Restore"] = "Restore",
        ["Window.Close"] = "Close", ["Window.Active"] = "Active window", ["Window.Inactive"] = "Inactive window",
        ["Project.Unnamed"] = "Untitled project",
        ["Project.Pristine"] = "New · not saved", ["Project.Modified"] = "Unsaved changes", ["Project.Saved"] = "Saved",
        ["Project.Tempo"] = "Tempo", ["Project.Meter"] = "Meter", ["Project.Bpm"] = "BPM",
        ["Preference.Language"] = "Language", ["Preference.Theme"] = "Theme",
        ["Preference.Dark"] = "Dark", ["Preference.Light"] = "Light",
        ["Preference.LoadFallback"] =
            "Preferences could not be fully read. Safe defaults are in use; existing files were preserved.",
        ["Preference.SaveFailed"] = "Preference was applied for this session but could not be saved.",
        ["Audio.Idle"] = "Audio inactive", ["Host.About"] = "About Seqvium",
        ["Workspace.Panes"] = "Panes",
        ["Workspace.KeyboardHint"] = "F6 / Ctrl+Tab: switch · Esc: leave · Ctrl+W: close",
        ["Pane.Inspector"] = "Project Inspector", ["Pane.Appearance"] = "Appearance",
        ["Pane.Actions"] = "Pane actions", ["Pane.Activate"] = "Activate", ["Pane.Restore"] = "Restore pane",
        ["Pane.Collapse"] = "Collapse pane", ["Pane.Close"] = "Close pane",
        ["Pane.DockLeft"] = "Dock left", ["Pane.DockRight"] = "Dock right", ["Pane.Float"] = "Float / undock",
        ["Pane.AllowDocking"] = "Allow docking",
        ["Pane.MoveHint"] = "Actions focused: Ctrl+Arrows move · +Shift resize",
        ["Inspector.Project"] = "Project", ["Inspector.Status"] = "Status", ["Inspector.Patterns"] = "Patterns",
        ["Inspector.Sounds"] = "Sounds", ["Inspector.Resources"] = "Resources",
        ["Workspace.LoadFallback"] =
            "Layout read incompletely; safe entries restored. Original file preserved; layout saving disabled this session.",
        ["Workspace.SaveFailed"] = "Workspace layout could not be saved; this session remains usable.",
        ["Host.Scope"] =
            "Import WAV, edit occurrence Gain, Play / Stop / Panic and Save / Open are available. The graphical node canvas and musical editors are deferred."
    }.ToFrozenDictionary(StringComparer.Ordinal);

    public static IReadOnlyDictionary<string, string> Russian { get; } = new Dictionary<string, string>
    {
        ["Workflow.ReadOnly"] = "Только чтение",
        ["Workflow.Details"] = "Источник и исполнение",
        ["Workflow.More"] = "Действия проекта",
        ["Workflow.Technical"] = "Технические подробности",
        ["Workflow.GainUnit"] = "Линейная амплитуда · 0–1 (1 = исходный уровень)",
        ["Workflow.NoSelection"] = "Объект не выбран",
        ["Workflow.Busy"] = "Выполняется операция.",
        ["Workflow.NoUndo"] = "Нет изменения для отмены.",
        ["Workflow.NoRedo"] = "Нет изменения для повтора.",
        ["Workflow.NoTransport"] = "Воспроизведение не активно.",
        ["Status.Ready"] = "Готово",
        ["Status.Playing"] = "Воспроизведение",
        ["Status.Stopped"] = "Остановлено",
        ["Status.Ended"] = "Завершено",
        ["Status.Preparing"] = "Подготовка…",
        ["Status.Importing"] = "Импорт…",
        ["Status.Saved"] = "Сохранено",
        ["Status.Cancelled"] = "Отменено",
        ["Status.Blocked"] = "Воспроизведение заблокировано",
        ["Status.Degraded"] = "Медиа или обработка недоступны",
        ["Status.SaveFailed"] = "Сохранение не удалось · изменения сохранены в сеансе",
        ["Status.OpenFailed"] = "Открытие не удалось · текущий проект сохранён",
        ["Status.ImportFailed"] = "Импорт не удался",
        ["Status.DeviceFault"] = "Сбой аудиовыхода",
        ["Status.ActionFailed"] = "Действие не удалось",
        ["Status.LastValid"] = "Предыдущее допустимое аудио",
        ["graph.invalid-gain"] = "Gain должен быть от 0 до 1.",
        ["graph.prepare-media"] = "Нужный WAV проекта отсутствует или повреждён.",
        ["graph.prepare-format"] = "Формат выхода или каналы графа не поддерживаются.",
        ["graph.prepare-budget"] = "Граф превышает допустимый бюджет исполнения.",
        ["graph.prepare-source"] = "Музыкальный источник нельзя безопасно воспроизвести.",
        ["graph.prepare-target"] = "Выберите доступный граф употребления.",
        ["graph.missing-capability"] = "Нужная обработка узла недоступна.",
        ["graph.required-input"] = "Обязательный вход графа не подключён.",
        ["graph.missing-output"] = "В графе не указан Output.",
        ["graph.missing-source"] = "В графе нет привязанного Source.",
        ["graph.unresolved-source"] = "Placement или Part источника недоступен.",
        ["graph.source-coverage"] = "Источники графа не покрывают все нужные Part.",
        ["graph.directed-cycle"] = "В графе есть неподдерживаемый цикл.",
        ["graph.unsupported-dependency"] = "В графе есть неподдерживаемые зависимости.",
        ["graph.unsupported-scope"] = "Эта область обработки не поддерживается.",
        ["graph.processing-limit"] = "В графе превышено число узлов или источников.",
        ["graph.invalid-declaration"] = "Описание узла несовместимо.",
        ["graph.unsupported-port"] = "Порт графа не поддерживается.",
        ["graph.missing-endpoint"] = "Соединённый узел или порт недоступен.",
        ["graph.incompatible-ports"] = "Соединённые порты несовместимы.",
        ["graph.duplicate-connection"] = "В графе есть повторное соединение.",
        ["graph.input-cardinality"] = "К входу графа подключено слишком много соединений.",
        ["graph.unreachable-source"] = "Source не связан с Output.",
        ["graph.aggregation"] = "Намерение смешивания в графе несогласовано.",
        ["graph.preparation-fault"] = "Подготовка графа завершилась ошибкой.",
        ["graph.preparation-timeout"] = "Подготовка графа не завершилась; остановите или откройте проект заново.",
        ["graph.execution-terminated"] = "Аудиоисполнение завершено из-за отказа.",
        ["Workflow.Import"] = "Импорт WAV",
        ["Workflow.CancelImport"] = "Отменить импорт",
        ["Workflow.LastValid"] = "Воспроизводится предыдущая допустимая версия",
        ["Workflow.Open"] = "Открыть",
        ["Workflow.Save"] = "Сохранить",
        ["Workflow.SaveAs"] = "Сохранить как",
        ["Workflow.Play"] = "Слушать",
        ["Workflow.Stop"] = "Стоп",
        ["Workflow.Panic"] = "Panic",
        ["Workflow.Undo"] = "Отменить",
        ["Workflow.Redo"] = "Повторить",
        ["Workflow.Discard"] = "Не сохранять",
        ["Workflow.Cancel"] = "Отмена",
        ["Workflow.Occurrence"] = "Музыкальное употребление",
        ["Workflow.Gain"] = "Gain (амплитуда)",
        ["Workflow.Empty"] = "Импортируйте WAV для создания музыкального употребления.",
        ["Workflow.Ready"] = "Готово · для воспроизведения нажмите «Слушать»",
        ["Workflow.Importing"] = "Импорт WAV…",
        ["Workflow.ImportFailed"] = "Импорт WAV не удался; проект сохранён",
        ["Workflow.EditFailed"] = "Изменение не удалось",
        ["Workflow.Cancelled"] = "Импорт отменён",
        ["Workflow.Saved"] = "Проект сохранён",
        ["Workflow.SaveFailed"] = "Сохранение не удалось; изменения остались в проекте",
        ["Workflow.OpenFailed"] = "Открытие не удалось; текущий проект сохранён",
        ["Workflow.Opened"] = "Проект открыт · для старта нажмите «Слушать»",
        ["Workflow.Degraded"] = "Медиа или обработка недоступны; проект остаётся доступен",
        ["Workflow.Preparing"] = "Подготовка канонического графа…",
        ["Workflow.Playing"] = "Воспроизведение выбранного употребления",
        ["Workflow.Stopped"] = "Остановлено",
        ["Workflow.Ended"] = "Воспроизведение завершено",
        ["Workflow.Blocked"] = "Воспроизведение заблокировано",
        ["Workflow.DeviceFault"] = "Сбой аудиовыхода · автоматического перезапуска нет",
        ["Workflow.DeviceInactive"] = "Выход не активен · системный выход Windows выбирается при старте",
        ["Workflow.CloseFailed"] = "Завершение не удалось; ресурсы остаются во владении",
        ["Workflow.ActionFailed"] = "Действие не удалось",
        ["Workflow.LocalFileRequired"] = "Выберите локальный файл.",
        ["Workflow.UnsavedTitle"] = "Несохранённый проект",
        ["Workflow.UnsavedPrompt"] = "Сохранить изменения перед закрытием или заменой проекта?",
        ["Window.Minimize"] = "Свернуть", ["Window.Maximize"] = "Развернуть", ["Window.Restore"] = "Восстановить",
        ["Window.Close"] = "Закрыть", ["Window.Active"] = "Активное окно", ["Window.Inactive"] = "Неактивное окно",
        ["Project.Unnamed"] = "Проект без названия",
        ["Project.Pristine"] = "Новый · не сохранён", ["Project.Modified"] = "Есть несохранённые изменения",
        ["Project.Saved"] = "Сохранён",
        ["Project.Tempo"] = "Темп", ["Project.Meter"] = "Размер", ["Project.Bpm"] = "BPM",
        ["Preference.Language"] = "Язык", ["Preference.Theme"] = "Тема",
        ["Preference.Dark"] = "Тёмная", ["Preference.Light"] = "Светлая",
        ["Preference.LoadFallback"] =
            "Настройки прочитаны не полностью. Используются безопасные значения; исходные файлы сохранены.",
        ["Preference.SaveFailed"] = "Настройка применена для этого сеанса, но сохранить её не удалось.",
        ["Audio.Idle"] = "Аудио не активно",
        ["Host.About"] = "О Seqvium",
        ["Workspace.Panes"] = "Панели",
        ["Workspace.KeyboardHint"] = "F6 / Ctrl+Tab: панели · Esc: выйти · Ctrl+W: закрыть",
        ["Pane.Inspector"] = "Инспектор проекта", ["Pane.Appearance"] = "Оформление",
        ["Pane.Actions"] = "Действия панели", ["Pane.Activate"] = "Активировать",
        ["Pane.Restore"] = "Восстановить панель",
        ["Pane.Collapse"] = "Свернуть панель", ["Pane.Close"] = "Закрыть панель",
        ["Pane.DockLeft"] = "Закрепить слева", ["Pane.DockRight"] = "Закрепить справа", ["Pane.Float"] = "Открепить",
        ["Pane.AllowDocking"] = "Разрешить закрепление",
        ["Pane.MoveHint"] = "Фокус на действиях: Ctrl+стрелки — сдвиг · +Shift — размер",
        ["Inspector.Project"] = "Проект", ["Inspector.Status"] = "Состояние", ["Inspector.Patterns"] = "Паттерны",
        ["Inspector.Sounds"] = "Звуки", ["Inspector.Resources"] = "Ресурсы",
        ["Workspace.LoadFallback"] =
            "Макет прочитан не полностью; допустимые панели восстановлены. Исходный файл сохранён; запись макета отключена в этом сеансе.",
        ["Workspace.SaveFailed"] = "Сохранить макет не удалось; панели доступны в текущем сеансе.",
        ["Host.Scope"] =
            "Доступны импорт WAV, Gain выбранного употребления, воспроизведение / Стоп / Panic и сохранение / открытие. Графический редактор узлов и музыкальные редакторы отложены."
    }.ToFrozenDictionary(StringComparer.Ordinal);
}
